library(tidyverse)

#CHAPTER 3

#The data used
mpg
#Scatter plot
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy))

#EXERCISES
# I don't see anything. That's because I don't map the points
# ggplot(data = mpg) creates an empty graph
ggplot(data = mpg)
#224 rows and 11 columns. Is the first line in the console.
mpg
#drv: f = front-wheel drive, r = rear wheel drive, 4 = 4wd
?mpg
#Scatter plot
ggplot(data = mpg) + geom_point(mapping = aes(x = hwy, y = cyl))
# Its not useful because you plot the type of car versus the type of drive, but without frequency
# Maybe counting drv for each class is better
ggplot(data = mpg) + geom_point(mapping = aes(x = class, y = drv))

#For each aesthetic, you use aes() to associate the name of the aesthetic with a variable to display
#Scatter plot using colors for class
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, color = class))
#Scatter plot using size for class (not reccommended for discrete variables)
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, size = class))
#Scatter plot using transparency for class
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, alpha = class))
#Scatter plot using different forms for class
#ggplot2 will only use six shapes at a time. By default, additional groups will go unplotted when you use the shape aesthetic
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, shape = class))
#Scatter plot using blue for class
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
#Scatter plot is red. Is not blue because of parentesis (blue inside aes). Blue is understood as legend.
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, color = "blue"))
#Categorical: manu, model, year, cyl, trans, drv, fl, class, cty, hwy. All the rest are continuous.
?mpg
#Doubles are continuous variables
mpg
#Colour is continuous, size is discrete and shape does not show anything.  A continuous variable can not be mapped to shape
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, color = displ))
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, size = displ))
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, shape = displ))
#Colour and size are showing at the same time, two scales.
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, color = displ, size = displ))
?geom_point
#Modify the thickness of the point
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, color = displ, stroke=2))
#Map all the points but with different colours if satisfy the condition or not
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, color = displ < 5, stroke=2))

#useful for categorical variables, is to split your plot into facets, subplots that each display one subset of the data.
#To facet your plot by a single variable, use facet_wrap(). The first argument of facet_wrap() should be a formula, which you create with ~ followed by a variable name (here “formula” is the name of a data structure in R, not a synonym for “equation”). The variable that you pass to facet_wrap() should be discrete.
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy)) + facet_wrap(~ class, nrow = 2)
#To facet your plot on the combination of two variables, add facet_grid() to your plot call. The first argument of facet_grid() is also a formula
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy)) + facet_grid(drv ~ cyl)

#Facet a continuous variable generates a lot of different graphs (one per value)
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy)) + facet_wrap(~ displ, nrow = 2)
#It shows the same thing but in a different way (no data in a certain x,y)
ggplot(data = mpg) + geom_point(mapping = aes(x = drv, y = cyl))
#Plot only using 3 axes using a grid
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy)) + facet_grid(drv ~ .)
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy)) + facet_grid(. ~ cyl)
#Its different. You can cluster better using facet. For large datasets is useful.
#For shorter data sets colours are better. Also is there are many classes (maybe excessive graphs?)
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy)) + facet_wrap(~ class, nrow = 2)
#What does nrow do? Layout, you define number of rows of graphs
#What does ncol do? Layour, you define number of columns of graphs
#What other options control the layout of the individual panels? Shrink the scales, labels for axes, direction, etc
#Why doesn’t facet_grid() have nrow and ncol arguments? Because its fixed
?facet_wrap
#When using facet_grid() you should usually put the variable with more unique levels in the columns. 
#Why? Better layout

#A geom is the geometrical object that a plot uses to represent data. People often describe plots by the type of geom that the plot uses. For example, bar charts use bar geoms, line charts use line geoms, boxplots use boxplot geoms, and so on. Scatterplots break the trend; they use the point geom. As we see above, you can use different geoms to plot the same data. The plot on the left uses the point geom, and the plot on the right uses the smooth geom, a smooth line fitted to the data.
#To change the geom in your plot, change the geom function that you add to ggplot().
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy))
ggplot(data = mpg) + geom_smooth(mapping = aes(x = displ, y = hwy))

#Every geom function in ggplot2 takes a mapping argument. However, not every aesthetic works with every geom. You could set the shape of a point, but you couldn’t set the “shape” of a line. On the other hand, you could set the linetype of a line. geom_smooth() will draw a different line, with a different linetype, for each unique value of the variable that you map to linetype.
ggplot(data = mpg) + geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))
#you can set the group aesthetic to a categorical variable to draw multiple objects. ggplot2 will draw a separate object for each unique value of the grouping variable. In practice, ggplot2 will automatically group the data for these geoms whenever you map an aesthetic to a discrete variable (as in the linetype example). It is convenient to rely on this feature because the group aesthetic by itself does not add a legend or distinguishing features to the geoms.
ggplot(data = mpg) + geom_smooth(mapping = aes(x = displ, y = hwy))
ggplot(data = mpg) + geom_smooth(mapping = aes(x = displ, y = hwy, group = drv))
ggplot(data = mpg) + geom_smooth(mapping = aes(x = displ, y = hwy, color = drv),show.legend = FALSE)

#To display multiple geoms in the same plot, add multiple geom functions to ggplot():
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy)) + geom_smooth(mapping = aes(x = displ, y = hwy))
#Imagine if you wanted to change the y-axis to display cty instead of hwy. You’d need to change the variable in two places, and you might forget to update one. You can avoid this type of repetition by passing a set of mappings to ggplot(). ggplot2 will treat these mappings as global mappings that apply to each geom in the graph. In other words, this code will produce the same plot as the previous code:
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + geom_point() + geom_smooth()
#If you place mappings in a geom function, ggplot2 will treat them as local mappings for the layer. It will use these mappings to extend or overwrite the global mappings for that layer only. This makes it possible to display different aesthetics in different layers.
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + geom_point(mapping = aes(color = class)) + geom_smooth()
#You can use the same idea to specify different data for each layer. Here, our smooth line displays just a subset of the mpg dataset, the subcompact cars. The local data argument in geom_smooth() overrides the global data argument in ggplot() for that layer only.
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + geom_point(mapping = aes(color = class)) + geom_smooth(data = filter(mpg, class == "subcompact"), se = FALSE)

#What geom would you use to draw a line chart? A boxplot? A histogram? An area chart?
#For example, bar charts use bar geoms, line charts use line geoms, boxplots use boxplot geoms
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv)) + geom_point() + geom_smooth(se = FALSE)
#What does show.legend = FALSE do? What happens if you remove it? Does not show the legend
#Why do you think I used it earlier in the chapter? Better vis
#What does the se argument to geom_smooth() do? Show a confidence interval
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv)) + geom_point() + geom_smooth()
?geom_smooth
#The same. Its only another way to do it (the first one is better in code and avoid mistakes)
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + geom_point() + geom_smooth()
ggplot() + geom_point(data = mpg, mapping = aes(x = displ, y = hwy)) + geom_smooth(data = mpg, mapping = aes(x = displ, y = hwy))

#Plots. I don't know how to do it the last one.
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + geom_point() + geom_smooth(se=FALSE)
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, group = drv)) + geom_point() + geom_smooth(se=FALSE)
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv)) + geom_point() + geom_smooth(se=FALSE)
ggplot() + geom_point(data = mpg, mapping = aes(x = displ, y = hwy, color=drv)) + geom_smooth(data = mpg, mapping = aes(x = displ, y = hwy), se=FALSE)
ggplot() + geom_point(data = mpg, mapping = aes(x = displ, y = hwy, color=drv)) + geom_smooth(data = mpg, mapping = aes(x = displ, y = hwy,linetype = drv), se=FALSE)

#Barcharts. Both do the same.
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut))
ggplot(data = diamonds) + stat_count(mapping = aes(x = cut))
#Barchart of proportion
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, y = ..prop.., group = 1))
#Barchart with stats
ggplot(data = diamonds) + stat_summary(mapping = aes(x = cut, y = depth),fun.ymin = min,fun.ymax = max,fun.y = median)

#EXCERCISES 3.7 MISSING

#There’s one more piece of magic associated with bar charts. You can colour a bar chart using either the colour aesthetic, or, more usefully, fill:
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, colour = cut))
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = cut))
#Note what happens if you map the fill aesthetic to another variable, like clarity: the bars are automatically stacked. Each colored rectangle represents a combination of cut and clarity.
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = clarity))
#The stacking is performed automatically by the position adjustment specified by the position argument. If you don’t want a stacked bar chart, you can use one of three other options: "identity", "dodge" or "fill".
# position = "identity" will place each object exactly where it falls in the context of the graph. This is not very useful for bars, because it overlaps them. To see that overlapping we either need to make the bars slightly transparent by setting alpha to a small value, or completely transparent by setting fill = NA.
ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) + geom_bar(alpha = 1/5, position = "identity")
ggplot(data = diamonds, mapping = aes(x = cut, colour = clarity)) + geom_bar(fill = NA, position = "identity")
#position = "fill" works like stacking, but makes each set of stacked bars the same height. This makes it easier to compare proportions across groups.
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = clarity), position = "fill")
#position = "dodge" places overlapping objects directly beside one another. This makes it easier to compare individual values.
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = clarity), position = "dodge")

#The values of hwy and displ are rounded so the points appear on a grid and many points overlap each other. This problem is known as overplotting. This arrangement makes it hard to see where the mass of the data is. Are the data points spread equally throughout the graph, or is there one special combination of hwy and displ that contains 109 values?
#You can avoid this gridding by setting the position adjustment to “jitter”. position = "jitter" adds a small amount of random noise to each point. This spreads the points out because no two points are likely to receive the same amount of random noise.
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy), position = "jitter")

#Aggregate smooth
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) + geom_point() + geom_smooth()
#width and height vary the amount of jittering
#Both represent in a different way the overlapping points. One agreggate randomness and the other count (could be use with size to represent more points concentrated)
?geom_jitter()
?geom_count()

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + geom_boxplot()

#EXCERCISES 3.8 MISSING
#EXCERCISES 3.9 MISSING


#CHAPTER 5

#First examples
library(nycflights13)
library(tidyverse)
library(rmarkdown)
nycflights13::flights
filter(flights, month == 1, day == 1)
jan1 <- filter(flights, month == 1, day == 1)
(dec25 <- filter(flights, month == 12, day == 25))
filter(flights, month = 1)
filter(flights, month == 11 | month == 12)
nov_dec <- filter(flights, month %in% c(11, 12))
filter(flights, !(arr_delay > 120 | dep_delay > 120))
filter(flights, arr_delay <= 120, dep_delay <= 120)

#Find all flights that
#Had an arrival delay of two or more hours
filter(flights, arr_delay > 120)
#Flew to Houston (IAH or HOU)
?flights
filter(flights, dest == "IAH" | dest=="HOU")
#Were operated by United, American, or Delta
filter(flights, carrier == "UA" | carrier == "AA" | carrier == "DA")
#Departed in summer (July, August, and September)
filter(flights, month == 7 |month == 8 | month == 9)
#Arrived more than two hours late, but didn’t leave late
filter(flights, arr_delay > 120,  !dep_delay > 0)
#Were delayed by at least an hour, but made up over 30 minutes in flight
filter(flights, arr_delay > 60, air_time > 30)
#Departed between midnight and 6am (inclusive)
filter(flights, dep_time>0000,dep_time<=0600)
#Another useful dplyr filtering helper is between(). What does it do? Can you use it to simplify the code needed to answer the previous challenges?
filter(flights, between(dep_time, 0000,0600)) 
#How many flights have a missing dep_time? What other variables are missing? What might these rows represent?
filter(flights, is.na(dep_time))
#Why is NA ^ 0 not missing? Why is NA | TRUE not missing? Why is FALSE & NA not missing? Can you figure out the general rule? (NA * 0 is a tricky counterexample!)


#Arrange rows
arrange(flights, year, month, day)
arrange(flights, desc(dep_delay))
#Missing values are always sorted at the end

#How could you use arrange() to sort all missing values to the start? (Hint: use is.na()).
#Sort flights to find the most delayed flights. Find the flights that left earliest.
arrange(flights, desc(dep_delay))
arrange(flights, desc(dep_time))
#Sort flights to find the fastest flights.
arrange(flights, air_time)
#Which flights travelled the longest? Which travelled the shortest?
arrange(flights, distance)
arrange(flights, desc(distance))

#Select columns by name
select(flights, year, month, day)
# Select all columns between year and day (inclusive)
select(flights, year:day)
# Select all columns except those from year to day (inclusive)
select(flights, -(year:day))
#use rename(), which is a variant of select() that keeps all the variables that aren’t explicitly mentioned:
rename(flights, tail_num = tailnum)
#select() in conjunction with the everything() helper. This is useful if you have a handful of variables you’d like to move to the start of the data frame.
select(flights, time_hour, air_time, everything())

#Brainstorm as many ways as possible to select dep_time, dep_delay, arr_time, and arr_delay from flights.
#What happens if you include the name of a variable multiple times in a select() call?
#What does the one_of() function do? Why might it be helpful in conjunction with this vector?
vars <- c("year", "month", "day", "dep_delay", "arr_delay")
#Does the result of running the following code surprise you? How do the select helpers deal with case by default? How can you change that default?
select(flights, contains("TIME"))

#mutate() always adds new columns at the end of your dataset so we’ll start by creating a narrower dataset so we can see the new variables. Remember that when you’re in RStudio, the easiest way to see all the columns is View().
flights_sml <- select(flights, year:day, ends_with("delay"), distance, air_time)
mutate(flights_sml,gain = dep_delay - arr_delay,speed = distance / air_time * 60)
#you can refer to columns that you’ve just created:
mutate(flights_sml,
       gain = dep_delay - arr_delay,
       hours = air_time / 60,
       gain_per_hour = gain / hours)
#If you only want to keep the new variables, use transmute()
transmute(flights,
gain = dep_delay - arr_delay,
hours = air_time / 60,
gain_per_hour = gain / hours
)
#Modular arithmetic: %/% (integer division) and %% (remainder)

#Currently dep_time and sched_dep_time are convenient to look at, but hard to compute with because they’re not really continuous numbers. Convert them to a more convenient representation of number of minutes since midnight.
transmute(flights, dep_time, sched_dep_time, dt = (dep_time %/% 100)*60 + dep_time %% 100, sdt = (sched_dep_time %/% 100)*60 + sched_dep_time %% 100)
#Compare air_time with arr_time - dep_time. What do you expect to see? What do you see? What do you need to do to fix it?
#Not the same values. You need to consider that after 24 the next hour is 0.
transmute(flights, air_time, dif=arr_time-dep_time)
#Compare dep_time, sched_dep_time, and dep_delay. How would you expect those three numbers to be related?
#dep_delay + sched_dep_time is the actual departed time
transmute(flights,dep_time, sched_dep_time, dep_delay)
#Find the 10 most delayed flights using a ranking function. How do you want to handle ties? Carefully read the documentation for min_rank().
x<-transmute(flights,dep_delay)
min_rank(desc(flights.dep_delay))
#What does 1:3 + 1:10 return? Why?
#Its a matrix and its sum
1:3+1:10
#What trigonometric functions does R provide?
#cospi(x), sinpi(x), and tanpi(x), compute cos(pi*x), sin(pi*x), and tan(pi*x)

#EXERCISS 5.6 MISSING
#EXERCISE 5.7 MISSING
